a bit of decopling, updated to use latest ECS scripts from upstream, fixed some shell script issues, spaces

diff --git a/bin/deployables b/bin/deployables
--- a/bin/deployables
+++ b/bin/deployables
@@ -1,12 +1,12 @@
 #!/bin/bash
-
+#
 # based on https://github.com/circleci/go-ecs-ecr/blob/master/deploy.sh
 
 ##
 ## configure debugging
 ##
 
-if [[ ! -z "${DEPLOY_DEBUG}" ]] ; then
+if [ ! -z "${DEPLOY_DEBUG}" ] ; then
     set -x
 fi
 
@@ -14,12 +14,6 @@ fi
 ##
 ## environment variables
 ##
-
-# circle v2 hack: source env file
-echo DEPLOY_ENV_FILE: $DEPLOY_ENV_FILE
-if [[ ! -z "${DEPLOY_ENV_FILE}" ]] ; then
-  source $DEPLOY_ENV_FILE
-fi
 
 #
 # optional
@@ -49,12 +43,12 @@ JQ="jq --raw-output --exit-status"
 
 function check_environment {
 
-    if [[ -z "${DEPLOY_AWS_ACCOUNT}" ]] ; then
+    if [ -z "${DEPLOY_AWS_ACCOUNT}" ] ; then
         echo "Error: DEPLOY_AWS_ACCOUNT is required"
         exit 1
     fi
 
-    if [[ -z "${DEPLOY_ECR_ACCOUNT}" ]] ; then
+    if [ -z "${DEPLOY_ECR_ACCOUNT}" ] ; then
         echo "Error: DEPLOY_ECR_ACCOUNT is required"
         exit 1
     fi
@@ -68,35 +62,19 @@ function aws_configure {
     echo
 
     if [[ -n $aws_configure_done ]]; then
-      return
+        return
     fi
 
-    if [[ -z "${DEPLOY_AWS_ACCOUNT}" ]] ; then
+    if [ -z "${DEPLOY_AWS_ACCOUNT}" ] ; then
         echo "Error: DEPLOY_AWS_ACCOUNT is required"
         exit 1
     fi
 
     aws --version
-#    aws configure set default.region ${DEPLOY_AWS_REGION}
-#    aws configure set default.output json
 
-    # circle v2 hack
-    if [[ ! -d ~/.aws ]] ; then
-        mkdir -p ~/.aws
+    mkdir -p '$(dirname $( eval echo -n $DEPLOY_AWS_CONFIG ))'
 
-        cat >> $( eval echo -n ~/.aws/credentials ) <<EOH
-[${DEPLOY_AWS_SOURCE_PROFILE}]
-aws_access_key_id=${AWS_ACCESS_KEY_ID}
-aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}
-EOH
-
-        cat >> $( eval echo -n $DEPLOY_AWS_CONFIG ) <<EOH
-[profile ${DEPLOY_AWS_SOURCE_PROFILE}]
-region=${DEPLOY_AWS_REGION}
-EOH
-    fi
-
-    cat >> $( eval echo -n $DEPLOY_AWS_CONFIG ) <<EOH
+    cat > '$( eval echo -n $DEPLOY_AWS_CONFIG )' <<EOH
 ## added by deployables.aws_configure()
 [profile ${DEPLOY_AWS_PROFILE}]
 role_arn = arn:aws:iam::${DEPLOY_AWS_ACCOUNT}:role/${DEPLOY_AWS_ROLE}
@@ -110,12 +88,19 @@ EOH
         exit 1
     fi
 
+    cat '$( eval echo -n $DEPLOY_AWS_CONFIG )'
+
     aws_configure_done=1
 }
 
 function aws_test_profile {
-  aws_configure
-  aws --profile=${DEPLOY_AWS_PROFILE} s3 ls
+    aws_configure
+    aws --profile=${DEPLOY_AWS_PROFILE} s3 ls
+}
+
+function aws_run () {
+    aws_configure
+    aws --profile=${DEPLOY_AWS_PROFILE} "${@:1}"
 }
 
 function ecr_login () {
@@ -130,23 +115,30 @@ function ecr_login () {
     # check environment variables
     check_environment
 
+    # Newer versions of docker don't work well with the default login args to aws-cli
+    email=""
+    if [[ $(docker --version) =~ 1(7|8)\. ]]; then
+        echo "Adding email remove flag"
+        email="--no-include-email"
+    fi
+
     login_command=$(
-        aws --profile=${DEPLOY_AWS_PROFILE} ecr get-login
+        aws --profile=${DEPLOY_AWS_PROFILE} ecr get-login $email
     )
 
-    if [[ ! "$login_command" =~ "https://${DEPLOY_AWS_ACCOUNT}" ]]; then
+    if [[ ! "$login_command" =~ https://${DEPLOY_AWS_ACCOUNT} ]]; then
         echo Error: Login command does not match DEPLOY_AWS_ACCOUNT: ${DEPLOY_AWS_ACCOUNT}
         echo Error: Check that DEPLOY_AWS_ROLE="${DEPLOY_AWS_ROLE}" is as valid role in DEPLOY_AWS_ACCOUNT="${DEPLOY_AWS_ACCOUNT}"
         echo login_command: ${login_command}
         return 1
     fi
 
-     login_command=$(
+    login_command=$(
         echo ${login_command} \
-        | sed -e "s/${DEPLOY_AWS_ACCOUNT}/${DEPLOY_ECR_ACCOUNT}/"
+            | sed -e "s/${DEPLOY_AWS_ACCOUNT}/${DEPLOY_ECR_ACCOUNT}/"
     )
 
-    if [[ ! "$login_command" =~ "https://${DEPLOY_ECR_ACCOUNT}" ]]; then
+    if [[ ! "$login_command" =~ https://${DEPLOY_ECR_ACCOUNT} ]]; then
         echo Error: Login command does not match DEPLOY_ECR_ACCOUNT: ${DEPLOY_ECR_ACCOUNT}
         echo login_command: ${login_command}
         return 1
@@ -214,7 +206,7 @@ function ecr_push_image () {
 
     docker push $image
 
-    if [[ $? != 0 ]] ; then
+    if [ $? != 0 ] ; then
         echo "Error: Unable to push image, ${image}"
         exit 1
     fi
@@ -222,17 +214,17 @@ function ecr_push_image () {
 }
 
 function ecs_update_task_image () {
-  ##
-  ## Updates just the imgage of an existing task
-  ##
+    ##
+    ## Updates just the imgage of an existing task
+    ##
 
-   #Avoid using echo as we use it to "return" the task arn from the function
+    #Avoid using echo as we use it to "return" the task arn from the function
 
     local image="$1"
     local family="$2"
 
     previous_task=$( \
-        aws ecs describe-task-definition \
+            aws ecs describe-task-definition \
             --profile ${DEPLOY_AWS_PROFILE} \
             --task-definition ${family}
     )
@@ -240,7 +232,7 @@ function ecs_update_task_image () {
     #create new task def json from previous task
 
     task_def=$( \
-        echo ${previous_task} | $JQ --arg IMAGE "${image}" '.taskDefinition.containerDefinitions[0].image = $IMAGE' \
+            echo ${previous_task} | $JQ --arg IMAGE "${image}" '.taskDefinition.containerDefinitions[0].image = $IMAGE' \
             | $JQ '.taskDefinition' \
             | $JQ 'del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities)'
     )
@@ -248,13 +240,13 @@ function ecs_update_task_image () {
     echo ${task_def}> fulltask_${family}.json
 
     register_task=$( \
-        aws ecs register-task-definition \
+            aws ecs register-task-definition \
             --profile ${DEPLOY_AWS_PROFILE} \
             --cli-input-json file://fulltask_${family}.json
     )
 
     task_arn=$( \
-        echo ${register_task} | $JQ '.taskDefinition.taskDefinitionArn'
+            echo ${register_task} | $JQ '.taskDefinition.taskDefinitionArn'
     )
 
     echo "export ECS_TASK_ARN_${family}=$task_arn" >> $BASH_ENV
@@ -265,8 +257,9 @@ function ecs_update_task_image () {
 
 function ecs_deploy_task () {
 
-    local image="$1"
+    local image_tag="$1"
     local subfamily="$2"
+    local image="${DEPLOY_ECR_HOST}/${DEPLOY_APP_NAME}:${image_tag}"
 
     echo
     echo Deploying ECS task
@@ -274,25 +267,17 @@ function ecs_deploy_task () {
     echo subfamily: ${subfamily}
     echo
 
-    if [[ -z "$subfamily" ]] ; then
+    if [ -z "$subfamily" ] ; then
         family="${DEPLOY_APP_NAME}"
-        service="${DEPLOY_APP_NAME}"
     else
         family="${DEPLOY_APP_NAME}-${subfamily}"
-        service="${DEPLOY_APP_NAME}-${subfamily}"
     fi
+    service="${family}"
 
     echo
     echo "Remembering current task definition, family: ${family}"
     echo
 
-    previous_version=$( \
-        aws ecs describe-services \
-            --profile ${DEPLOY_AWS_PROFILE} \
-            --cluster ${DEPLOY_ECS_CLUSTER_NAME} \
-            --services ${service} \
-            | $JQ '.services[0].taskDefinition' \
-    )
 
     echo
     echo "Registering new task definition, family: ${family}"
@@ -306,37 +291,46 @@ function ecs_deploy_task () {
     fi
 
     task_def=$( \
-        DEPLOY_IMAGE_NAME=${image} \
-        DEPLOY_ECS_CLUSTER_NAME=${DEPLOY_ECS_CLUSTER_NAME} \
-        DEPLOY_SUBFAMILY=${subfamily} \
-        DEPLOY_AWS_REGION=${DEPLOY_AWS_REGION} \
-        ${DEPLOY_ENVSUBST_COMMAND:-envsubst} < "${task_def_template}"
+            DEPLOY_IMAGE_NAME=${image} \
+            DEPLOY_IMAGE_TAG=${image_tag} \
+            DEPLOY_ECS_CLUSTER_NAME=${DEPLOY_ECS_CLUSTER_NAME} \
+            DEPLOY_SUBFAMILY=${subfamily} \
+            DEPLOY_AWS_REGION=${DEPLOY_AWS_REGION} \
+            DEPLOY_APP_NAME=${family} \
+            ${DEPLOY_ENVSUBST_COMMAND:-envsubst} < "${task_def_template}"
     )
+
+    echo "Deploying Task Def: $(echo $task_def | $JQ .)"
 
     if [[ -z "${DEPLOY_TASK_ROLE_ARN}" ]] ; then
         revision_target=$( \
-            aws ecs register-task-definition \
+                aws ecs register-task-definition \
                 --profile ${DEPLOY_AWS_PROFILE} \
                 --container-definitions "$task_def" \
                 --family "${family}" \
                 | $JQ '.taskDefinition.taskDefinitionArn' \
-        )
+            )
     else
         revision_target=$( \
-            aws ecs register-task-definition \
+                aws ecs register-task-definition \
                 --profile ${DEPLOY_AWS_PROFILE} \
                 --task-role-arn "${DEPLOY_TASK_ROLE_ARN}" \
                 --container-definitions "$task_def" \
                 --family "${family}" \
                 | $JQ '.taskDefinition.taskDefinitionArn' \
-        )
+            )
     fi
 
-    if [[ -z "$revision_target" ]] ; then
+    if [ -z "$revision_target" ] ; then
         echo "Failed to register task definition"
         exit 1
     fi
     echo "Target Revision: $revision_target"
+
+
+    if [ ! -z "${DEPLOY_NO_SERVICE}" ] ; then
+        exit
+    fi
 
     echo
     echo Updating service
@@ -345,7 +339,7 @@ function ecs_deploy_task () {
     echo
 
     revision_actual=$( \
-        aws ecs update-service \
+            aws ecs update-service \
             --profile ${DEPLOY_AWS_PROFILE} \
             --cluster ${DEPLOY_ECS_CLUSTER_NAME} \
             --service ${service} \
@@ -353,7 +347,7 @@ function ecs_deploy_task () {
             | $JQ '.service.taskDefinition' \
         )
 
-    if [[ "$revision_target" != "$revision_actual" ]] ; then
+    if [ "$revision_target" != "$revision_actual" ] ; then
         echo "Error updating service. Target does not match actual: ${revision_target} != ${revision_actual} "
         exit 1
     fi
@@ -369,7 +363,7 @@ function ecs_verify_deploy () {
 
     local subfamily="$1"
 
-    if [[ -z "$subfamily" ]] ; then
+    if [ -z "$subfamily" ] ; then
         family="${DEPLOY_APP_NAME}"
         service="${DEPLOY_APP_NAME}"
     else
@@ -387,17 +381,17 @@ function ecs_verify_deploy () {
     echo
 
     # wait for older revisions to disappear
-    for attempt in {1..60}; do
+    for ((n=0;n<100;n++)); do
 
         revision_deployed=$( \
-            aws ecs describe-services \
+                aws ecs describe-services \
                 --profile ${DEPLOY_AWS_PROFILE} \
                 --cluster ${DEPLOY_ECS_CLUSTER_NAME} \
                 --services ${service} \
                 | $JQ ".services[0].deployments | .[] | select(.taskDefinition != \"$revision_target\") | .taskDefinition" \
             )
 
-        if [[ -z "$revision_deployed" ]] ; then
+        if [ -z "$revision_deployed" ] ; then
             echo "Success: Deployed!"
             return 0
         fi
@@ -405,7 +399,7 @@ function ecs_verify_deploy () {
         echo "Waiting for update:"
         echo "  revision_target: ${revision_target}"
         echo "  revision_deployed: ${revision_deployed}"
-        sleep 5
+        sleep 6
 
     done
 
@@ -426,12 +420,12 @@ function docker_build {
     echo DEPLOY_DOCKER_LOCAL_TAG: ${DEPLOY_DOCKER_LOCAL_TAG}
     echo
 
-    if [[ -z "${DEPLOY_DOCKERFILE}" ]] ; then
+    if [ -z "${DEPLOY_DOCKERFILE}" ] ; then
         echo "Error: DEPLOY_DOCKERFILE is required"
         return 1
     fi
 
-    if [[ -z "${DEPLOY_DOCKER_LOCAL_TAG}" ]] ; then
+    if [ -z "${DEPLOY_DOCKER_LOCAL_TAG}" ] ; then
         echo "Error: DEPLOY_DOCKER_LOCAL_TAG is required"
         return 1
     fi
@@ -479,20 +473,13 @@ function docker_build {
 
 }
 
-function ecs_deploy () {
 
-    # check environment variables
-    check_environment
-
-    # setup aws
-    aws_configure
-    ecr_login
-
+function _deploy_image () {
     #
     # push images
     #
 
-    if [[ ! -z "${DEPLOY_RETAG_AND_PUSH}" ]] ; then
+    if [ ! -z "${DEPLOY_RETAG_AND_PUSH}" ] ; then
 
         remote_tag="${DEPLOY_ECR_HOST}/${DEPLOY_APP_NAME}:${DEPLOY_RETAG_REMOTE_TAG}"
         target_tag="${DEPLOY_ECR_HOST}/${DEPLOY_APP_NAME}:${DEPLOY_RETAG_TARGET_TAG}"
@@ -513,8 +500,6 @@ function ecs_deploy () {
         ecr_push_image \
             $target_tag
 
-        DEPLOY_IMAGE="${target_tag}"
-
     else
 
         target_tag="${DEPLOY_ECR_HOST}/${DEPLOY_APP_NAME}:$( date +%Y%m%d )-${DEPLOY_SHA1}"
@@ -531,7 +516,7 @@ function ecs_deploy () {
         ecr_push_image \
             $target_tag
 
-        if [[ ! -z "$DEPLOY_PUSH_SECONDARY_TAG" ]] ; then
+        if [ ! -z "$DEPLOY_PUSH_SECONDARY_TAG" ] ; then
 
             secondary_tag="${DEPLOY_ECR_HOST}/${DEPLOY_APP_NAME}:${DEPLOY_PUSH_SECONDARY_TAG}"
 
@@ -548,30 +533,38 @@ function ecs_deploy () {
                 $secondary_tag
         fi
 
-        DEPLOY_IMAGE="${target_tag}"
-
     fi
 
-    if [[ -z "${DEPLOY_IMAGE}" ]] ; then
-        echo "Error: deploy image is undefined, DEPLOY_IMAGE=${DEPLOY_IMAGE}"
-        exit 1
+}
+
+
+function _update_service() {
+    if [ ! -z "$DEPLOY_PUSH_SECONDARY_TAG" ] ; then
+        DEPLOY_IMAGE_TAG="${DEPLOY_PUSH_SECONDARY_TAG}"
+    else
+        if [ ! -z "${DEPLOY_RETAG_AND_PUSH}" ] ; then
+            DEPLOY_IMAGE_TAG="${DEPLOY_RETAG_TARGET_TAG}"
+        else
+            DEPLOY_IMAGE_TAG="$( date +%Y%m%d )-${DEPLOY_SHA1}"
+        fi
     fi
+
 
     #
     # deploy task defs
     #
 
     # deploy all the tasks first...
-    if [[ -z "$DEPLOY_ECS_FAMILIES" ]] ; then
+    if [ -z "$DEPLOY_ECS_FAMILIES" ] ; then
 
-        ecs_deploy_task $DEPLOY_IMAGE
+        ecs_deploy_task $DEPLOY_IMAGE_TAG
         ecs_verify_deploy
 
     else
 
         for family in $DEPLOY_ECS_FAMILIES
         do
-            ecs_deploy_task $DEPLOY_IMAGE $family
+            ecs_deploy_task $DEPLOY_IMAGE_TAG $family
         done
 
         for family in $DEPLOY_ECS_FAMILIES
@@ -582,6 +575,44 @@ function ecs_deploy () {
     fi
 
 }
+
+function ecs_deploy_image () {
+
+    # check environment variables
+    check_environment
+
+    # setup aws
+    aws_configure
+    ecr_login
+
+    _deploy_image
+}
+
+function ecs_update_service () {
+
+    # check environment variables
+    check_environment
+
+    # setup aws
+    aws_configure
+    ecr_login
+
+    _update_service
+}
+
+function ecs_deploy () {
+
+    # check environment variables
+    check_environment
+
+    # setup aws
+    aws_configure
+    ecr_login
+
+    _deploy_image
+    _update_service
+}
+
 
 function lambda_package_zip () {
 
@@ -680,34 +711,34 @@ function lambda_update_from_s3 () {
 
     # update lambda function
     lambda_function_sha256=$( \
-        aws lambda update-function-code \
+            aws lambda update-function-code \
             --profile "${DEPLOY_AWS_PROFILE}" \
             --function-name "${DEPLOY_LAMBDA_TARGET_FUNCTION_NAME:-$DEPLOY_LAMBDA_FUNCTION_NAME}" \
             --s3-bucket "${DEPLOY_LAMBDA_S3_BUCKET}" \
             --s3-key "${DEPLOY_LAMBDA_FUNCTION_NAME}/${DEPLOY_LAMBDA_FUNCTION_NAME}.zip" \
-        | $JQ ".CodeSha256"
+            | $JQ ".CodeSha256"
     )
 
     if [[ -z "${lambda_function_sha256}" ]] ; then
-      echo "Error: Failed to update lambda function"
-      exit 1
+        echo "Error: Failed to update lambda function"
+        exit 1
     fi
 
     if [[ ! -z "${DEPLOY_LAMBDA_ZIP_VERSION}" ]] ; then
 
-      lambda_function_version=$( \
-        aws lambda publish-version \
-            --profile "${DEPLOY_AWS_PROFILE}" \
-            --function-name "${DEPLOY_LAMBDA_TARGET_FUNCTION_NAME:-$DEPLOY_LAMBDA_FUNCTION_NAME}" \
-            --description "${DEPLOY_LAMBDA_ZIP_VERSION} created by deployables" \
-            --code-sha-256 "${lambda_function_sha256}" \
-        | $JQ ".Version"
-      )
+        lambda_function_version=$( \
+                aws lambda publish-version \
+                --profile "${DEPLOY_AWS_PROFILE}" \
+                --function-name "${DEPLOY_LAMBDA_TARGET_FUNCTION_NAME:-$DEPLOY_LAMBDA_FUNCTION_NAME}" \
+                --description "${DEPLOY_LAMBDA_ZIP_VERSION} created by deployables" \
+                --code-sha-256 "${lambda_function_sha256}" \
+                | $JQ ".Version"
+        )
 
-      if [[ -z "${lambda_function_version}" ]] ; then
-        echo "Error: Failed to publish lambda version"
-        exit 1
-      fi
+        if [[ -z "${lambda_function_version}" ]] ; then
+            echo "Error: Failed to publish lambda version"
+            exit 1
+        fi
 
     fi
 
@@ -750,12 +781,12 @@ function lambda_deploy () {
     lambda_env_template="${DEPLOY_LAMBDA_FUNCTION_ENV_TEMPLATE:-environment.txt}"
 
     lambda_env=$( \
-        ${DEPLOY_ENVSUBST_COMMAND:-envsubst} < "${lambda_env_template}"
+            ${DEPLOY_ENVSUBST_COMMAND:-envsubst} < "${lambda_env_template}"
     )
 
     # create lambda function
     lambda_function_arn=$( \
-        aws lambda create-function \
+            aws lambda create-function \
             --profile "${DEPLOY_AWS_PROFILE}" \
             --function-name "${DEPLOY_LAMBDA_FUNCTION_NAME}" \
             --description "${DEPLOY_LAMBDA_FUNCTION_DESCRIPTION}" \
@@ -773,7 +804,7 @@ function lambda_deploy () {
     if [[ -z "$lambda_function_arn" ]] ; then
 
         lambda_function_arn=$( \
-            aws lambda update-function-configuration \
+                aws lambda update-function-configuration \
                 --profile "${DEPLOY_AWS_PROFILE}" \
                 --function-name "${DEPLOY_LAMBDA_FUNCTION_NAME}" \
                 --description "${DEPLOY_LAMBDA_FUNCTION_DESCRIPTION}" \
@@ -839,9 +870,9 @@ function lambda_deploy_event () {
 
     # create or update a cloudwatch event rule
     if jq -e . >/dev/null 2>&1 <<<"${DEPLOY_LAMBDA_EVENT_RULE}" ; then
-      # using json file!
+        # using json file!
         event_rule_arn=$( \
-            aws events put-rule \
+                aws events put-rule \
                 --profile "${DEPLOY_AWS_PROFILE}" \
                 --cli-input-json "${DEPLOY_LAMBDA_EVENT_RULE}" \
                 | $JQ ".RuleArn"
@@ -849,7 +880,7 @@ function lambda_deploy_event () {
     else
         # using schedule expression (direct)
         event_rule_arn=$( \
-            aws events put-rule \
+                aws events put-rule \
                 --profile "${DEPLOY_AWS_PROFILE}" \
                 --name "${event_rule_name}" \
                 --schedule-expression "${DEPLOY_LAMBDA_EVENT_RULE}" \
@@ -863,7 +894,7 @@ function lambda_deploy_event () {
         --function-name "${lambda_function_arn}" \
         --statement-id "${permission_statement_id}" \
 
-    # give permissions (statement id needs to be consistent string for this rule)
+        # give permissions (statement id needs to be consistent string for this rule)
     aws lambda add-permission \
         --profile "${DEPLOY_AWS_PROFILE}" \
         --function-name "${lambda_function_arn}" \
@@ -874,7 +905,7 @@ function lambda_deploy_event () {
 
     # add the lambda target to the rule
     failed_entry_count=$( \
-        aws events put-targets \
+            aws events put-targets \
             --profile "${DEPLOY_AWS_PROFILE}" \
             --rule "${event_rule_name}" \
             --targets "[{ \"Id\" : \"${lambda_event_basename}_target\", \"Arn\": \"${lambda_function_arn}\" ${DEPLOY_LAMBDA_TARGET_INPUT_JSON:+,\"Input\": \"${input_json_escaped}\"}}]" \
@@ -889,12 +920,12 @@ function lambda_deploy_event () {
 
 function deploy_lambda () {
     echo "Deprecated: Please use lambda_deploy()"
-    deploy_lambda
+    lambda_deploy "$@"
 }
 
 function deploy_lambda_event () {
     echo "Deprecated: Please use lambda_deploy_event()"
-    lambda_deploy_event
+    lambda_deploy_event "$@"
 }
 
 ##
@@ -902,4 +933,4 @@ function deploy_lambda_event () {
 ##
 
 # call arguments verbatim:
-$@
+"$@"
