Deploy S3 lambdas

diff --git a/bin/deployables b/bin/deployables
--- a/bin/deployables
+++ b/bin/deployables
@@ -584,13 +584,49 @@ function copy_lambda_to_s3 () {
       aws --profile "${DEPLOY_AWS_PROFILE}" \
           s3 cp \
           ${DEPLOY_LAMBDA_ZIP_FULLPATH} \
-          s3://${DEPLOY_LAMBDA_S3_BUCKET}/${DEPLOY_LAMBDA_FUNCTION_NAME}/${DEPLOY_LAMBDA_FUNCTION_NAME}-${DEPLOY_LAMBDA_ZIP_VERSION}.zip
+          s3://${DEPLOY_LAMBDA_S3_BUCKET}/${DEPLOY_LAMBDA_FUNCTION_NAME}/${DEPLOY_LAMBDA_FUNCTION_NAME}.zip
 
       if [[ "$?" != "0" ]] ; then
           echo "Error: Failed to copy lambda zip to S3 (${DEPLOY_LAMBDA_ZIP_VERSION})"
           exit 1
       fi
 
+    fi
+
+}
+
+function deploy_lambda_s3 () {
+    # check environment variables
+    if [ -z "${DEPLOY_AWS_ACCOUNT}" ] ; then
+        echo "Error: DEPLOY_AWS_ACCOUNT is required"
+        exit 1
+    fi
+
+    if [ -z "${DEPLOY_LAMBDA_FUNCTION_NAME}" ] ; then
+        echo "Error: DEPLOY_LAMBDA_FUNCTION_NAME is required"
+        exit 1
+    fi
+
+    if [ -z "${DEPLOY_LAMBDA_S3_BUCKET}" ] ; then
+        echo "Error: DEPLOY_LAMBDA_S3_BUCKET is required"
+        exit 1
+    fi
+
+    # setup aws
+    aws_configure
+
+    # update lambda function
+    lambda_function_arn=$( \
+        aws lambda update-function-code \
+            --profile "${DEPLOY_AWS_PROFILE}" \
+            --function-name "${DEPLOY_LAMBDA_FUNCTION_NAME}" \
+            --s3-bucket "${DEPLOY_LAMBDA_S3_BUCKET}" \
+            --s3-key "${DEPLOY_LAMBDA_FUNCTION_NAME}/${DEPLOY_LAMBDA_FUNCTION_NAME}.zip" #fix-me
+    )
+
+    if [[ -z "$lambda_function_arn" ]] ; then
+      echo "Error: Failed to deploy lambda function"
+      exit 1
     fi
 
 }
